### ISSUE TITLE
RPI3 examples/python properties

### ISSUE THREAD

**Issue by cappelaere** [TheImagingSource/tiscamera#112]
** (properties:2060): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "properties", line 415, in <module>
    main()
  File "properties", line 404, in main
    win = CameraVideo()
  File "properties", line 82, in __init__
    self.scroll_window.set_overlay_scrolling(False)
AttributeError: 'ScrolledWindow' object has no attribute 'set_overlay_scrolling'

**Comment by TIS-Stefan** [comment]
Hello and sorry for the delay. The error is caused by the old Linux Distribution. You have to options:
Simply change the sample, so the GUI does not long complain or update your Linux. I would change the Python sample code, because this error message is about GUI only and does not affect the camera and GStreamer functionallity.

Stefan
