### ISSUE TITLE
DMX33UX250 grabbed frame data have been offseted

### ISSUE THREAD

**Issue by hookhutao** [TheImagingSource/tiscamera#139]
![test_bad](https://user-images.githubusercontent.com/34904478/34399986-a180f276-ebc7-11e7-963b-34eb92081887.jpg)

this picture is grabbed when set_video_format: format=Y800,width=2448,height=2048,framerate=15.000000,
but the frame data is ok when set_video_format: format=Y800,width=640,height=480,framerate=30.000000

is there any properties needed to be set?

**Comment by TIS-Stefan** [comment]
Hello and I am very sorry for not answering.

The image is corrupted, because a data block is missing.  This happens, if the USB controller can not save its data into computers memory and therefore does not pick up all frames in time. 

If possible, I would use a lower frame rate, so the camera does not overwrite its internal USB buffers.

Stefan
