### ISSUE TITLE
[DFK27BUR0135] Opencv Windows vs ubuntu16.04

### ISSUE THREAD

**Issue by gonzalesluisfrancisco** [TheImagingSource/tiscamera#175]
Dear TIS team,
 I am writing an script which has to work on Ubuntu16.04. The first step that I take is write an script to show a video

import numpy as np  
import cv2  
cap = cv2.VideoCapture(1)  
while(True):  
    ret, frame = cap.read()  
    cv2.imshow('video1', frame)  
    if cv2.waitKey(1) & 0xFF == ord('q'):  
        break  
cap.release()  
cv2.destroyAllWindows()  

This script on Windows shows a color video but on Ubuntu it shows a gray video.
Something similar happen when I try to run the example "opencv.py" on my Ubuntu system which give me a list of format but all are gray scale.

Thanks in advance.
Luis Gonzales

**Comment by TIS-Stefan** [comment]
Hello

I am very sorry, I was on an exhibition the last week, therefore, I did not saw your issue. 

You see a grayscale video, because cv::VideoCapture does not set a video format. So the camera uses the first it has, which is usually GRAY8 (Y800). I am no OpenCV expert, therefore, I did not figured out, how to select a video format with OpenCV. However, only the DFK 33U cameras will provide YUY2, Y411 and some of them RGB24 colored.  The other models provide Bayer RAW, which must be debayered in the computer. For this task, we made our GStreamer modules. 
I made a Python sample, that wraps the Gstreamer code and shows, how to get the images into cv::Mat.

[pixelfix_opencv.zip](https://github.com/TheImagingSource/tiscamera/files/1966972/pixelfix_opencv.zip)

"TIS.py" is the wrapper, "Program.py" is the interesting part. You must to the TIS constructor the serial number, width, height and frame rate.

Stefan
