### ISSUE TITLE
Launch Multiple Cameras

### ISSUE THREAD

**Issue by eros-ck** [TheImagingSource/tiscamera#186]
I have connected the computer with two cameras and configured them for different IPs.

They are both detected. But when I start the gstreamer by running `gst-launch-1.0 tcambin ! videoconvert ! autovideosink`, only one camera's is used.

Could you show me how to use multiple cameras at the same time?

**Comment by TIS-Stefan** [comment]
Hello

It is expected, that you can use only one camera per gst-launch-1.0 pipeline. You start two  pipelines and pass the serial numbers of the camera to the tcambin in order to see both streams in parallel.
```
gst-launch-1.0 tcambin serial=12345678 ! videoconvert ! ximagesink
gst-launch-1.0 tcambin serial=87654321 ! videoconvert ! ximagesink
```
tcam-ctrl -l lists the cameras and their serial numbers.
You may open for each pipeline an own terminal.

If both cameras are connected to the same bus controller, you may use half frame rate only, otherwise you wont get images.
```
gst-launch-1.0 tcambin serial=12345678 ! video/x-raw, width=w, height=h,framerate=fps ! videoconvert ! ximagesink
gst-launch-1.0 tcambin serial=87654321 ! video/x-raw, width=w, height=h,framerate=fps ! videoconvert ! ximagesink
```
Where w=width in pixel, h = height in pixel, fps = half of maximum fps, e.g 15/1. 
I would have posted running pipelines, but I do not know, which camera models you use.

Stefan
