### ISSUE TITLE
Can't keep 30 frames-per-second over time <case:454579>

### ISSUE THREAD

**Issue by yoelk** [TheImagingSource/tiscamera#203]
- OS: Ubuntu 16.04
- python: 3.6
- TIS version: 0.9.1
- TIS version source: https://github.com/TheImagingSource/tiscamera/releases/download/v-release-candidate-0_9_1-1/tiscamera_0.9.1_amd64.deb
- Camera type: DMK Z12GX236
- test code: https://gist.github.com/yoelk/5ff12e10f0ab2f0e5665e74f86e5f4a5
- The code is based on Two-cams.zip which I found here: https://github.com/TheImagingSource/tiscamera/issues/117

The test code starts the camera with 1920x1080 resolution and 30 FPS.
- It periodically prints the measured FPS rate.
- If time between two frames is bigger than a certain threshold value (200 ms) it prints a log as well.

Two problems:
1. The FPS doesn't reach 30. It starts at 15 and keeps it for a while
2. After a while (after 13 FPS prints in the `print log` in the gist), the FPS dramatically drops and delays of over 200 ms are reported.

This is very problematic and becoming quite urgent for us, as we need the camera to keep this FPS (at this resolution) for weeks long.

Can someone please look into this?

Thanks a lot!
Joel

**Comment by TIS-Arne** [comment]
This is not how video capture should work. The "last-sample" property of a sink element gives you exactly that: The last sample seen by the element. There is no queue of "last-sample" buffers in the element so you will just miss images. 

The "opencv.py" example shows how to use the appsink element correctly: https://github.com/TheImagingSource/tiscamera/blob/master/examples/python/opencv.py

I modified this example to print the achieved frame rate every 30 frames here:
https://gist.github.com/TIS-Arne/76452cb32b3284984282da596ce3602a

**Comment by yoelk** [comment]
Dear Arne, thanks for the example.
The code you sent indeed works at 30 FPS, but it sometimes has short freezes (a delay between frames of ~200 ms).

We continued to examine C++ examples (see this [issue](https://github.com/TheImagingSource/tiscamera/issues/204)) and also there, these delays were found.

Here is the [modified C++ example](https://gist.github.com/yoelk/11b233b6f286d9a70a20b23184c8b5b8) I'm using. Please tell me if this is reproducible in your side.

The problematic frames are reported as seen below. Please notice that after a late frame, all of the late frames come at once, so that the overall FPS remains ~30:
```
----------------- LATE frame: 234 ms
good frame: 0 ms
good frame: 0 ms
good frame: 0 ms
good frame: 0 ms
good frame: 1 ms
```

I think you'd agree this is not the expected behavior.

**This poses a big problem for us** as we've already invested a lot of time for the integration of TIS cameras in our product, but **we can not continue if this isn't fixed** or worked around.

Thank you for your support!
Joel

**Comment by TIS-Arne** [comment]
Those late frames may happen if some of the data packets transmitted by the camera get lost, either on the network or on the system itself. The driver detects the missing packets and asks the camera to re-transmit the missing data. However you should only see a delay of about one frame in this situation, so something in the order of 66 ms (unless packets of two subsequent frames get dropped). 

If the packet loss is on the system itself, it might happen because the network driver collecting the video packets is running in user space with user space priority. Could you please run your test program like so:
```
sudo chrt --rr 99 ./tcam_demo  <SERIAL_NUMBER>
```
This will run the application with realtime priority on your system. Please let me know if this fixes the issue.
We are looking into ways to allow the capturing thread of the application with realtime priority without the need to run it with the "chrt" command.

**Comment by yoelk** [comment]
Thanks for the tip!
I've used this command and it improved but didn't solve the problem completely.
Late frames still happen sometimes, but less often.

Any other possibility you might think of?
Could you try to reproduce this in your offices?

**Comment by TIS-Arne** [comment]
Like I said, the late frames happen if network packets are dropped. If this still happens when your application is running with realtime permissions, you could try the following steps to isolate the issue: 
Directly connect the camera to the target computer, without any other network devices present on the same network. This could be done by using a separate network interface for the camera. 
If packet loss occurs even if the camera is on a separate network, you should try a different machine to rule out hardware issues. 
Disable the video display to check whether it affects the performance of the application.

Please let me know whether any of those steps remedy the issue.

**Comment by yoelk** [comment]
Another thought: If the PoE switch might be involved in the delays, it might be better to try and run the camera powered with an external source. I've noticed that there is a second connector (I assume for power supply) near the Ethernet port. When can I find the specifications for this cable? I assume this is for the 12VDC supply written in the [camera's fact sheet](https://s1-dl.theimagingsource.com/api/2.5/packages/documentation/factsheets-single/fsdmkz12gx236/3061c612-50cb-5d8a-8b47-7447e7b4651e/fsdmkz12gx236.en_US.pdf)

**Comment by yoelk** [comment]
We've reproduced the issue exactly with another PC, where instead of a PoE switch there is a PoE injector between the PC and the camera.

Did you try to reproduce this in your offices?
If it doesn't happen to you, we must be able to find the differences between your PC and ours.

Thanks!

**Comment by yoelk** [comment]
Dear Arne,
Today I've captured communication between the camera and the PC, in order to try and track the problem.

Two issues I've found (I can attach the sniff files if you're interested, I'm using `Wireshark`):

1. Increasing the MTU from 1500 to 9000 didn't results in the sending of Jumbo frames from the camera to the PC. The Ethernet packets size increase from 1630 to 1862 bytes.

2. During late frames, indeed there is a resend of packets. The PC asks the camera to resend a bunch of packets, but the camera doesn't do it so the PC asks again (5 times in total). It seems like after these 5 times, the PC decides to stop waiting and releases to the software the packets it saved since the resend-requests started. While I don't know why the camera doesn't resend the packets (indeed they were missing in the stream), this seems to me like something that can be worked around.
Would it be possible to ask the driver NOT to ask resend-requests? It's much less problematic for us loosing a single frame once in a while, but having 200ms (which correlates to waiting 5-6 frames) freezes becomes an issue.

Does that seem like something you could help us achieve?

Thanks for your support,
Joel

**Comment by yoelk** [comment]
Update regarding the first point (MTU):
In the capture, I don't see any attempt from the camera to send jumbo packets, even though the MTU for the Ethernet port is defined to be 9000.
Might this be some configuration error of the camera? How can we tell the camera that the MTU has increased?

**Comment by TIS-Arne** [comment]
@yoelk: I made a mistake with this camera. This model does not support "package resend". As you say it looks like the video frames are not actually lost but there is a ~200ms pause and all of the frames come at once afterwards. Since there is no package resend, this delay could not happen on the network side. Instead it looks like something on your machine is blocking the execution of the capture pipeline for this amount of time. 
Could you try to make sure there is no background activity on the system at all? Maybe using a clean Ubuntu installation or a Ubuntu live image and see if the result is the same? Also could you please tell me which systems you are using the camera on?

**Comment by yoelk** [comment]
1. So why is the PC asking for a package resend? Is this a bug in your driver?
[Here](https://drive.google.com/open?id=1gVlGkuSVMTgDHlu6Isak6TvqvhhqldM7) you can see 5 screenshots of the 5 attempts of my PC to ask the camera to resend packets.
As you can see in the screenshots, the packets were indeed missing.

2. Regardless if the camera fails to send packets sometimes, or the PC's Ethernet driver dumps them sometimes, I need from you a patch for the driver so that the PC simply ignores such problematic frames. This is the simplest workaround I can think of. Or if there is already a configuration command I can use to achieve that (e.g. reduce the number of resend attempts to 0), that would help as well.

3. Did you try to reproduce this problem with this camera model in your PC? Can you please verify if this happens for you as well or only for us?

4. I think it is more important at the moment to work around this issue, because even if it doesn't happen in your PC (please verify) it does happen to two of our development PCs, both strong machines with plenty of memory and new processors (mine is based on ASUS-99 motherboard and an Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz processor).
So before breaking our heads about what are the differences between the PC settings, please help us to work around this issue. Making fresh PCs and checking it again and again is not the way to go here.

**Comment by TIS-Arne** [comment]
Regarding 1: I do not have permission to see the files. Google should have sent you an email asking for the permissions. 

Regarding 2: The driver should not ask the camera to resend the packages since the camera does not support package resend. We will investigate. 

Regarding 3: I tried to reproduce the issue with the same camera model and a fairly low end machine: Intel(R) Core(TM) i3-4158U CPU @ 2.00GHz
I get a single missing frame some times - ie. the application reads "----------------- LATE frame: 66 ms" in this case without a subsequent "good frame 0ms". This might be due to network traffic though - the camera is not on a separate network here right now. I was unable to reproduce longer timeouts or the situation where images with a delay of 0ms come in after a LATE frame.

Regarding 4: Since we do not know the cause, I can not come up with a work around. We will investigate the package resend issue. Still you should rule out the possibility that a background process on your machine may cause the blocking.

**Comment by yoelk** [comment]
1. Sorry for that, the files should be available now.

2. Thanks!

3. ok

4. Looking at the sniffing files, I do not see any communications from my
PC other than with the camera. I'll have a closed look tomorrow to see if
any pattern is visible.

Also adding no.5 here:
Setting the MTU in my PC had hardly any effect on the packet size. Can you
confirm this happens on your side as well? Can this be changed by some
configuration? Or firmware update?

Thanks again! Joel

**Comment by TIS-Arne** [comment]
@yoelk I overlooked that you are using the 0.9.1 package version  of tiscamera. This version is quite outdated. Could you please check out the current master branch from the tiscamera repository and try again?

**Comment by yoelk** [comment]
Thanks for the comment. Indeed, as a general policy we use release versions of 3rd party code.
I've moved to the latest tag (v-tiscamera-0.10.0) and it does behave better:
1. I also get now ~66ms delays instead of ~200ms

Still unsolved:
2. Still get late frames some times, one in a few minutes. When not running with `chrt --rr 99` it becomes worse.
3. **MTU setting does not make the camera send jumbo frames** (as described in my last comment). Can you please verify this point? I believe this issue might be the root of all other issues. If jumbo frames would be sent, the network traffic might be affected so that no frames get lost anymore.

Thanks,
Joel

**Comment by yoelk** [comment]
Hi again, did you get my last response?
Thanks

**Comment by TIS-Arne** [comment]
To enable the debug output, please set the following environment variable:
```
TCAM_LOG=DEBUG
```

**Comment by TIS-Arne** [comment]
@yoelk This is a version of tiscamera for testing: It enables realtime priority for the network capture thread. Also the tcamsrc element now has a property that allows the incomplete /corrupted frames to be delivered to the application. We are still working on a way to pass the information which frame got corrupted. 

[tiscamera-build.zip](https://github.com/TheImagingSource/tiscamera/files/2328659/tiscamera-build.zip)

**Comment by yoelk** [comment]
Thanks!

**Comment by yoelk** [comment]
Hi,
I've tested the new version and unfortunately don't see any change.
Might it be because:
- I use `tcambin` and not `tcamsrc`?
- I should activate this feature (allowing incomplete frames) somewhere? I couldn't find documentation about it so assumed it's automatically activated.

btw, I'm running now with the camera directly connected to the PC (no switch) and using an external power cable.

If you'll send again a version, perhaps it's better that I build it locally, so I can look at the modified code.

Thanks again,
Joel

**Comment by yoelk** [comment]
Thanks Edgar!
Will these logs be printed also when this flag is True?
I haven't seen any related logs in the terminal up to now.

Will try setting this flag now

**Comment by TIS-Edgar** [comment]
Hi Joel,

In the default situation (drop-incomplete-buffer=true) a message `Stream has missing packets.` will appear.
When setting drop-incomplete-buffer=false an additional message `Image has missing packets. Sending incomplete buffer as requested.` should appear. If this message does not appear then no incomplete buffers are being sent.

**Comment by yoelk** [comment]
Is there a way in TIS to verify which version is installed?
Running a very basic C++ sample code (based on your examples) I still get sometimes lost frames, but don't see any of the logs you're referring to.
I do get many other logs:
```
2214289744 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2216731343 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2216731445 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2219192364 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2219192536 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2221647062 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
2221647168 <ERROR> /src/tiscamera/src/utils.cpp:305: Could not open file "/var/lock/gige-daemon.lock"
```

I'd just like to verify that the installation process went well and that indeed I'm running the right version here.

Thanks

**Comment by TIS-Edgar** [comment]
Hi Joel,

At the beginning of the log output should be a message which describes the version that is run.
Yours should be:
```
The following library versions are used:
	Tcam:	0.10.0_development/8d320e0_rev_2300
	Aravis:	0.6_version_c56e530
```

I am currently looking into the log spam and other issues you mentioned in #212 .

**Comment by yoelk** [comment]
I wrote you about this [here](https://github.com/TheImagingSource/tiscamera/issues/212).
I'm not sure where can I see these startup logs.
