### ISSUE TITLE
Record video approach

### ISSUE THREAD

**Issue by dernster** [TheImagingSource/tiscamera#243]
Hi,

What would be a good approach for supporting live streaming and at the same time being able to record a video based on a user action? I'm wondering if the only way to achieve this would be by building a specific gstreamer pipeline.

My camera model is DFK Z12G445.

Thanks!

**Comment by TIS-Stefan** [comment]
Hello 

You are right, building a suitable pipeline is the first step. Unfortunately I do not have such a pipeline sample, therefore (I do not really dare to suggest this) is searching in the internet for appropriate samples.
After the tcambin you add a "tee" filter, so you can split the pipeline into display and avi capture path.
I would not directly create a AVI capture directly after the "tee" module, because this is somewhat hard to control by user interaction. I would add an appsink. In the Appsink handler the images are forward to an "appsrc", if the user wants to capture AVI. I thought, we had a sample for that, but I can not find it any more. 

However, maybe your questions are more basic, so please feel free to ask.

Stefan

**Comment by dernster** [comment]
Thanks for the response @TIS-Stefan, so basically the idea would be to split the main live streaming pipeline using a tee that goes to an appsink. From there, if I receive a "start capturing" event from the user I would start feeding another pipeline (just for recording) which its src element is an appsrc element right?

**Comment by TIS-Stefan** [comment]
Hi

Yes, that would be the general approach I would use.

Which programming language do you prefer? C++ or Pyhton?

Stefan

**Comment by TIS-Stefan** [comment]
Ok,

you may start with the samples https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples

Stefan

**Comment by dernster** [comment]
Thank you @TIS-Stefan

**Comment by TIS-Stefan** [comment]
Come back to me, when we shall go into the coding details.
