### ISSUE TITLE
Set TCAM_CAPTURE_PY_INSTALL to new location if unable to find matching site

### ISSUE THREAD

**Issue by jassib** [TheImagingSource/tiscamera#278]
Currently if you try to specify your own cmake install prefix, you will get an index error:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range`. This is due to `print[x for x in site.getsitepackages() if x.startswith('${CMAKE_INSTALL_PREFIX}/lib')][0]` in `tiscamera/tools/tcam-capture/CMakeLists.txt: `. If the list is empty, there will be an index error.

**Comment by TIS-Edgar** [comment]
That is indeed a bug. I'll try to unify the configuration of python module installation paths for the different tools (tcam-capture, tcam-gigetool) so that future version will have less points of error. 
I will also introduce a variable that allows an overwrite of the installation path. Something like `TCAM_INSTALL_PYTHON3_MODULES`. In the mean time your patch is merged, thank you very much for!
