### ISSUE TITLE
Image Callback Function - Appsink is pulling samples out of order

### ISSUE THREAD

**Issue by manindermatharoo** [TheImagingSource/tiscamera#282]
Hello,

I don't know if this is an issue or not but I'm seeing this behavior with the callback function implemented from this example: https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/master/Save%20an%20image%20using%20OpenCV%20in%20C%2B%2B/main.cpp in the new_frame_cb function.

When I signal a software capture, I see that the callback function is called for a software capture at 2.2 seconds before a software capture issued at 2.0 seconds since the program started. The callback for the later software capture happens before the one issued beforehand. Don't know if this is a GStreamer issue or tiscamera issue.

**Comment by TIS-Stefan** [comment]
Hello

I suppose, with "software capture" you mean software trigger.
The sample you point to does not enable the trigger mode. Therefore the callback is called as soon as the camera is started, because the camera provides images and they are forwarded to the callback.
You need two properties. The "Trigger Mode" and the "Software Trigger"
```
    // Query the trigger mode property. Attention: The "Trigger Mode" name
    // can be different on USB and GigE camera. 
    std::shared_ptr<Property> TriggerMode = cam.get_property("Trigger Mode");


    // Query the software trigger property. Attention: The "Software Triggere" name
    // can be different on USB and GigE camera. 
    std::shared_ptr<Property> Softwaretrigger = cam.get_property("Software Trigger");
```

Then the camera is started and the trigger mode enabled. In this situation, you may get one unwanted first image, which you can discard in your callback handler.
```

    // Start the camera
    cam.start();

    // Enable trigger mode. Must be done after the camera start, because 
    // Aravis likes to reset the trigger mode on camera start.
    TriggerMode->set(cam,"On");
```
Now no new images are provided by the camera, until a trigger occurs. The software trigger is fired as
```
        Softwaretrigger->set(cam,1);
```
However, I have the faint suspect, that here could be a faint misunderstanding, because I do not know, whether this is, was you want. Therefore, you may describe, what you want to program,

Stefan
