### ISSUE TITLE
DFK23up1300 with opencv cv2.VideoCapture gives monochromactic output

### ISSUE THREAD

**Issue by lvgeng** [TheImagingSource/tiscamera#322]
Hi there.

I am using opencv-python 4.1.1 with the camera.

I tried to use 

cap=cv2.VideoCapture(0)
ret, frame = cap.read()

to get the output of the camera.
but I got monochromactic images. And I checked the data the three channel gives same value for the same pixel, so it's not Bayer data.

The camera should be a color one, what should I do to deal with this?

My goal is to capture color image without any auto adjustment, but the following sample showed it has a lot auto-adjustment and the image quality is much lower compared with the monochromactic images. (I have changed the encoding kernel to (1, 1), still some horizontal lines.)
  
https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/tree/master/Snap%20an%20Image%20and%20convert%20to%20OpenCV%20in%20Python

https://www.theimagingsource.com/products/industrial-cameras/usb-3.0-color/dfk23up1300/

**Comment by TIS-Stefan** [comment]
Hello

You get Bayer Raw data. with the correct paramters to  cvtColor(OpenCVImage,ColorCVImage,cv::COLOR_BayerGR2RGB);
you will get a green colored image. I am not sure, which is the correct start pattern specified 
 by cv::COLOR_BayerGR2RGB and the similar ones.

The image will be greenish, because the camera does not perform white balance. This is to be done in software, therefore, we made our GStreamer modules. The DFK 33UP1300 does this onboard.

You could compile OpenCV with GStreamer support and pass a GStreamer pipeline to cv::videocapture():

```
const char *pipeline = "tcambin serial=19410125 ! video/x-raw, formart=BGRx, width=1280,height=960, framerate=30/1 ! videoconvert ! appsink";
cv::VideoCapture *cap = new cv::VideoCapture(pipeline);
```
This should result in a correct RGB32 image.

Alternatively you use GStreamer and pass the correct image to OpenCV as shown at https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/tree/master/Save%20an%20image%20using%20OpenCV%20in%20C%2B%2B

Stefan
