### ISSUE TITLE
(gscam:3262): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed

### ISSUE THREAD

**Issue by Heyinsen** [TheImagingSource/tiscamera#331]
```
(gscam:3262): GStreamer-WARNING **: 0.10-style raw video caps are being created. Should be video/x-raw,format=(string).. now.

(gscam:3262): GStreamer-CRITICAL **: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed

(gscam:3262): GStreamer-CRITICAL **: gst_structure_get_int: assertion 'structure != NULL' failed

(gscam:3262): GStreamer-CRITICAL **: gst_structure_get_int: assertion 'structure != NULL' failed
OpenCV Error: Assertion failed (s >= 0) in setSize, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp, line 310
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp:310: error: (-215) s >= 0 in function setSize

[rqt_reconfigure-6] process has finished cleanly
log file: /home/z/.ros/log/505b5cac-3999-11ea-83b1-503eaadf3bb1/rqt_reconfigure-6*.log
```

when i want to run a project, i met this problem and i don't know how to solve this problem. Could you tell me where this problems lies in.

**Comment by TIS-Stefan** [comment]
I must admit, I do not know, because you did not tell me "where this problems lies in.", which means, you did not tell me, what you are doing.
Guesswork:
you try the ros example code. I think it is no needed anymore, because the gst plugin of ROS supports GStreamer 1.0 these days.
Also, as the error message says, your video format caps is Gstreamer 0.10 not 1.0. The error message gives an explanation what it should look like.

For more ROS help, please let me know:
- which ROS module do you use? A link to the documentation of it will be helpful, since I am not a ROS user.
- which pipeline do you use in the (forgotten name) environment variable?
- which camera do you use?

Stefan
