### ISSUE TITLE
USB cable for DFM 37UX226-ML

### ISSUE THREAD

**Issue by Moj-Dev** [TheImagingSource/tiscamera#387]
I'm using [this USB cable](https://www.londondrugs.com/certified-data-premium-usb-3.1-type-c-to-usb-3.0-a-female---guc05-1000/L6473672.html) for 37UX226 camera and couldn't get frames over 14FPS in RGB32(4000x3000). The problem is the cable? Should I use only the[ TIS USB3.1 cable](https://www.theimagingsource.com/products/cables/usb-3.1/causb31acbls3/)?

**Comment by TIS-Stefan** [comment]
Hello

Its a good question. Which software do yo use? Maybe the software or computer is too slow for debayering the 12Megapixel image.

Stefan

**Comment by Moj-Dev** [comment]
Software: IC Capture 2.5 on Windows 10
Laptop: Lenovo Y7000P-1060

**Comment by TIS-Stefan** [comment]
This is the Linux issue area. 

However, check for power saving mechanism and try to disable them. 
Also let me know, what the four numbers in the status bar, right corner of IC Capture, show.

**Comment by Moj-Dev** [comment]
I wanted to test what you have said, but I got an error. "The device 'DFM 37UX226-ML' is in live mode, but it does not deliver images". 
![Capture](https://user-images.githubusercontent.com/58832214/102262290-bb7ede80-3ec7-11eb-8a8a-77d04a71005b.JPG)

I changed the format and frame rate, none of them worked and I can not get any frames!
This camera is the MOST USERENEMY PRODUCT I've ever seen! First, there were lots of blue dots in the frames and as I discussed with you, I returned it and got another one. Then, your claim about getting 30 FPS in full resolution was not correct, and now it doesn't work for no reason!

**Comment by TIS-Stefan** [comment]
Hello

You are not the only user of this camera. But you are the only one, having these issues.
Which USB cable do you use? If you use a cable provided with a mobil phone, then you wont get images, because these cables are usually USB 2.0 only.

At least, there is always the option to give the camera back, if you are not able to get images.

**Comment by Moj-Dev** [comment]
The camera worked for a while with [this USB3.0 cable ](https://www.londondrugs.com/certified-data-premium-usb-3.1-type-c-to-usb-3.0-a-female---guc05-1000/L6473672.html). 
I've ordered your cable and going to test it.

**Comment by TIS-Stefan** [comment]
If a camera worked for a while and then does not, then something must have changed.
Question is, what?
I would have a look by teamviewer on your computer, but I suppose, we are on different time zones, teamviewer logins are shared by email and I will be on holidays for next two weeks.

Some more hints:
Windows 10

- Check with "winver" the Windows version.
If 1607, Anniversary Update: It blocks USB cameras. It is fixed by Windows Updates, thus perform updates.

- Virus Scanner
Check for virus scanner blocking webcam streams. e.g. Kaspersky Endpoint Security and ESET do so.

**Comment by Moj-Dev** [comment]
I tried the camera with TIS USB cable both on Windows 10 (Version 1809) and Ubuntu 18.04, It didn't work! I tried with all formats and framerate, none of them worked! Also, tried another PC with Windows OS, it was the same!

**Comment by TIS-Stefan** [comment]
Hello

Did you sent the camera in to your camera dealer for checking? Maybe it is broken somehow?

Stefan
