### ISSUE TITLE
TextOverlay hides the video stream

### ISSUE THREAD

**Issue by daktmacfan** [TheImagingSource/tiscamera#422]
if I use the following pipe line it works great in both gst-lauch as well as my C++ program using QTGStreamer.

`gst-launch-1.0 tcamsrc ! xvideo/x-bayer,width=1920,height=1080,framerate=15/1  ! tcamautoexposure ! tcamwhitebalance ! bayer2rgb ! videoconvert ! xvideosink`
`
If I try to add a simple **textoverlay** it hides the video stream.

`gst-launch-1.0 tcamsrc ! xvideo/x-bayer,width=1920,height=1080,framerate=15/1  ! tcamautoexposure ! tcamwhitebalance ! 
bayer2rgb ! videoconvert ! textoverlay font-desc="Sans 24" text="test string" valignment=top halignment=left ! xvideosink
`

Is this a bug, or am I doing something wrong?  If this is a known issue is there another way I can add text perhaps?

Thanks!

**Comment by TIS-Stefan** [comment]
Hello

it works perfectly on my Linux. But I do not have a "xvideosink", I use "xvimagesink" instead.
So maybe it is a QTGStreamer issue? I installed this with
sudo apt-get install qtgstreamer-plugins-qt5
but I do not get an "xvideosink".
Thus, you may to use "xvimagesink" instead of "xvideosink" in the pipeline and see, what happens. 

Stefan

**Comment by TIS-Edgar** [comment]
Closed due to inactivity.
