### ISSUE TITLE
Error after running gst-launch-0.10 <...> command!

### ISSUE THREAD

**Issue by arthurjonathan** [TheImagingSource/tiscamera#44]
Hello,
I am getting the following error after applying gstreamer command.

root@arthur-MXE5400:~/tiscamera/src#gst-launch-0.10 v4l2src ! video/x-raw-gray,width=640,height=480,framerate=15/1 ! tisvideobufferfilter ! tis_auto_exposure ! tiscolorize ! queue ! tiswhitebalance ! queue ! bayer2rgb ! queue ! ffmpegcolorspace ! ximagesink
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data flow error.
Additional debug info:
gstbasesrc.c(2625): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming task paused, reason not-negotiated (-4)
Execution ended after 562734982 ns.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

Is anyone come along with this problem before?

**Comment by TIS-Stefan** [comment]
Hello

please exchange  "tis_auto_exposure ! tiscolorize"   against  "tiscolorize ! tis_auto_exposure".

Also I would like you to update the "src" directory and rebuild our pipeline modules.

Stefan

**Comment by swetham92** [comment]
I am also facing the same problem/error message while trying to use gst-launch with the odroid board (ubuntu version 15.04). However the same pipeline worked with a desktop PC with Ubuntu version 12.04 installed in it. I had followed the same steps outlined in the below link in both the cases. And the camera module I am using is Imaging source camera DFK 22BUC03.
Link-
https://github.com/TheImagingSource/tiscamera/wiki/Getting-Started-with-USB-2.0-cameras-on-a-Raspberry-PI-or-on-other-Linux-Systems

The pipeline I used was-
gst-launch-0.10 v4l2src ! video/x-raw-gray ! tisvideobufferfilter !  tiscolorize ! tis_auto_exposure ! queue ! tiswhitebalance ! queue ! bayer2rgb ! queue ! ffmpegcolorspace ! ximagesink

Please give appropriate suggestions so that I can get the problem rectified at the earliest.

Thanks & regards

**Comment by TIS-Stefan** [comment]
Hello

what happens, if you remove the "tis_auto_exposure"?

Stefan

**Comment by swetham92** [comment]
The error message remains still the same after removing tis_auto_exposure. Sorry for the trouble in posting it in multiple places.
