### ISSUE TITLE
v0.14.y bugfix branch

### ISSUE THREAD

**Issue by g0hl1n** [TheImagingSource/tiscamera#503]
Dear TheImagingSource team,
would it be possible to set up a permanent "bugfix"/"stable" branch for the 0.14.y release?
We have one project were we (unfortunately) need to use the v0.14 release and need at least one fix to build it correctly (see https://github.com/g0hl1n/tiscamera/tree/bugfix-0.14.y).

Therefore I wanted to ask you if it would be possible to set up such a branch in your repository to allow creating PRs against it?

Thanks & regards;

**Comment by TIS-Edgar** [comment]
Hi g0hl1n,

> Therefore I wanted to ask you if it would be possible to set up such a branch in your repository to allow creating PRs against it?

Absolutely!

I added the following branches:

release/0.14
release/1.0

Every future release will receive a branch so that we can ensure release specific fixes can be added.
Thus future releases will add branches 'release/X.Y'.

The branch release/0.14 uses the last commit (0b84e380) before the 1.0 merge.
The two additional commits are to ensure that the project compiles (basically your changes) and that packages can be built.

I will also add a pull request template so that contributors will know where to put their requests.

Is this sufficient to ensure your project can stay in working order or are there additional steps we can take to assist you?

**Comment by g0hl1n** [comment]
Great! Thank you @TIS-Edgar.
This is basically exactly the thing I was aiming for :wink: 

I will do some tests but I assume everything should be working with this branch again!

Thanks again.
